events {}

http
{
    server
    {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_prefer_server_ciphers on;
        
        location / {
            return 200 'NGINX container working\n';
        }
    }
}