events {}

http
{
    server
    {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        location / {
            return 200 'NGINX container working\n';
        }
    }
}