services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mariadb_data: 
networks:
  inception:
    driver: bridge