FROM debian:bookworm

RUN apt update && \
    apt install -y mariadb-server mariadb-client && \
    apt clean

COPY tools/setup.sh /setup.sh

RUN chmod +x /setup.sh

EXPOSE 3306

ENTRYPOINT ["/setup.sh"]