FROM debian:bullseye

RUN apt update && \
    apt install -y \
    php-fpm \
    php-mysql \
    php-cli \
    curl \
    mariadb-client && \
    apt clean

RUN curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    -o /usr/local/bin/wp && \
    chmod +x /usr/local/bin/wp

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf
COPY ./tools/setup.sh ./setup.sh

RUN chmod +x setup.sh

EXPOSE 9000

ENTRYPOINT ["/setup.sh"]